export const qk = {
  me: ['auth', 'me'] as const,
  devices: ['auth', 'devices'] as const,
  deviceRequests: ['auth', 'device-requests'] as const,
  center: ['center'] as const,
  members: ['center', 'members'] as const,
  groups: ['groups'] as const,
  group: (id: string) => ['groups', id] as const,
  myGroups: ['groups', 'mine'] as const,
  students: ['students'] as const,
  student: (id: string) => ['students', id] as const,
  teachers: ['teachers'] as const,
  teacher: (id: string) => ['teachers', id] as const,
  teacherDashboard: ['teacher', 'dashboard'] as const,
  attendance: (params?: object) => ['attendance', params ?? {}] as const,
  homework: (groupId?: string) => ['homework', 'list', groupId ?? 'all'] as const,
  homeworkOne: (id: string) => ['homework', id] as const,
  grade: (id: string) => ['grades', id] as const,
  debates: ['arena'] as const,
  debate: (id: string) => ['arena', id] as const,
  notifications: ['notifications'] as const,
}
